name: Java CI with Maven
on:
 push:
  branches: [main]
jobs:
 builds:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build Java package
      run: mvn clean install -f Javarepo1/pom.xml
    - name: SonarCloud Scan
      run: mvn sonar:sonar -Dsonar.projectKey=renuka1217 -Dsonar.organization=renuka1217 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=renuka1217 -Dsonar.token=9c70fdd5f96264024dd1fc92a1267a812db09c6f
